package main

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

func GeneratePDFReport(testRun *TestRun, timeSeries []TimeSeriesPoint) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Title
	pdf.SetFont("Arial", "B", 24)
	pdf.SetTextColor(37, 99, 235) // PipeOps blue
	pdf.Cell(40, 10, "PipeOps Load Test Report")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(40, 6, "Performance Analysis Report")
	pdf.Ln(15)

	// Test Information
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(40, 8, "Test Information")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 10)

	info := []struct {
		Label string
		Value string
	}{
		{"Host:", testRun.Host},
		{"Total Users:", fmt.Sprintf("%d", testRun.TotalUsers)},
		{"Ramp Up:", fmt.Sprintf("%d seconds", testRun.RampUpSec)},
		{"Duration:", fmt.Sprintf("%d seconds", testRun.Duration)},
		{"Status:", testRun.Status},
		{"Started At:", testRun.StartedAt.Format("2006-01-02 15:04:05")},
	}

	if testRun.CompletedAt != nil {
		info = append(info, struct {
			Label string
			Value string
		}{"Completed At:", testRun.CompletedAt.Format("2006-01-02 15:04:05")})
	}

	for _, item := range info {
		pdf.Cell(50, 6, item.Label)
		pdf.Cell(0, 6, item.Value)
		pdf.Ln(6)
	}

	pdf.Ln(5)

	// Performance Metrics
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(40, 8, "Performance Metrics")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 10)

	metrics := []struct {
		Label string
		Value string
	}{
		{"Total Requests:", fmt.Sprintf("%d", testRun.TotalRequests)},
		{"Success Count:", fmt.Sprintf("%d", testRun.SuccessCount)},
		{"Error Count:", fmt.Sprintf("%d", testRun.ErrorCount)},
		{"Success Rate:", fmt.Sprintf("%.2f%%", float64(testRun.SuccessCount)/float64(testRun.TotalRequests)*100)},
		{"Average Latency:", fmt.Sprintf("%.2f ms", testRun.AvgLatency)},
		{"Min Latency:", fmt.Sprintf("%.2f ms", testRun.MinLatency)},
		{"Max Latency:", fmt.Sprintf("%.2f ms", testRun.MaxLatency)},
		{"Requests Per Second:", fmt.Sprintf("%.2f", testRun.RPS)},
	}

	for _, metric := range metrics {
		pdf.Cell(50, 6, metric.Label)
		pdf.Cell(0, 6, metric.Value)
		pdf.Ln(6)
	}

	pdf.Ln(5)

	// Time Series Summary
	if len(timeSeries) > 0 {
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(40, 8, "Time Series Summary")
		pdf.Ln(8)
		pdf.SetFont("Arial", "", 9)

		// Table header
		pdf.SetFillColor(200, 200, 200)
		pdf.CellFormat(40, 6, "Time", "1", 0, "C", true, 0, "")
		pdf.CellFormat(30, 6, "RPS", "1", 0, "C", true, 0, "")
		pdf.CellFormat(30, 6, "Avg Latency", "1", 0, "C", true, 0, "")
		pdf.CellFormat(30, 6, "Success %", "1", 0, "C", true, 0, "")
		pdf.CellFormat(30, 6, "Requests", "1", 0, "C", true, 0, "")
		pdf.Ln(6)

		pdf.SetFillColor(255, 255, 255)
		pdf.SetFont("Arial", "", 8)

		// Show sample points (every 5 seconds or max 20 rows)
		step := len(timeSeries) / 20
		if step < 1 {
			step = 1
		}
		if step > 5 {
			step = 5
		}

		for i := 0; i < len(timeSeries); i += step {
			point := timeSeries[i]
			pdf.CellFormat(40, 5, point.Timestamp.Format("15:04:05"), "1", 0, "C", false, 0, "")
			pdf.CellFormat(30, 5, fmt.Sprintf("%.2f", point.RPS), "1", 0, "C", false, 0, "")
			pdf.CellFormat(30, 5, fmt.Sprintf("%.2f ms", point.AvgLatency), "1", 0, "C", false, 0, "")
			pdf.CellFormat(30, 5, fmt.Sprintf("%.1f%%", point.SuccessRate), "1", 0, "C", false, 0, "")
			pdf.CellFormat(30, 5, fmt.Sprintf("%d", point.Requests), "1", 0, "C", false, 0, "")
			pdf.Ln(5)
		}
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(100, 116, 139) // Gray
	pdf.Cell(0, 10, fmt.Sprintf("Generated by PipeOps Load Tester - %s | pipeops.io", time.Now().Format("2006-01-02 15:04:05")))

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
